apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: portfolio-secrets
  namespace: portfolio-prod
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: portfolio-secrets
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app: portfolio
          managed-by: external-secrets-operator
          environment: prod

  data:
    - secretKey: db-url
      remoteRef:
        key: portfolio/prod
        property: db-url

    - secretKey: db-username
      remoteRef:
        key: portfolio/prod
        property: db-username

    - secretKey: db-password
      remoteRef:
        key: portfolio/prod
        property: db-password

    - secretKey: jwt-secret
      remoteRef:
        key: portfolio/prod
        property: jwt-secret

    - secretKey: redis-host
      remoteRef:
        key: portfolio/prod
        property: redis-host
