apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-secrets
  namespace: argocd
  labels:
    app: portfolio
    component: secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Wave 1 : après external-secrets-operator (wave 0)
    # ClusterSecretStore (wave 1) et ExternalSecrets (wave 2) sont dans ce dossier
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  # Source : dossier k8s/external-secrets/ dans ce repo
  # Contient : ClusterSecretStore + ExternalSecret dev + ExternalSecret prod
  source:
    repoURL: https://github.com/amine77/devsecops-angular-java21-aws.git
    targetRevision: main
    path: k8s/external-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets    # ClusterSecretStore est cluster-wide mais réside ici

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
