apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base commune backend + frontend + ingress
# Les overlays (dev/prod) surchargent namespace, images, replicas, host

resources:
  - backend/
  - frontend/
  - ingress.yaml
