{{- if .Values.hpa.enabled }}
# HPA Backend
{{- if .Values.backend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "portfolio.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.backendLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "portfolio.fullname" . }}-backend
  minReplicas: {{ .Values.hpa.backend.minReplicas }}
  maxReplicas: {{ .Values.hpa.backend.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.backend.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.backend.targetMemoryUtilizationPercentage }}
{{- end }}
---
# HPA Frontend
{{- if .Values.frontend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "portfolio.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.frontendLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "portfolio.fullname" . }}-frontend
  minReplicas: {{ .Values.hpa.frontend.minReplicas }}
  maxReplicas: {{ .Values.hpa.frontend.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.frontend.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
