{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "portfolio.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}

  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}

  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.backend.enabled }}
          # API backend — /api/* → backend service (avec rewrite)
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "portfolio.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          {{- end }}
          {{- if .Values.frontend.enabled }}
          # Frontend Angular — tout le reste
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "portfolio.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
          {{- end }}
{{- end }}
